In [1]:
import jovian

<IPython.core.display.Javascript object>

In [2]:
jovian.commit(filename='numpy.ipynb')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "nikhil956839/numpy" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/nikhil956839/numpy


'https://jovian.ai/nikhil956839/numpy'

In [1]:
#Temperatures, Rainfall & Humidity of different cities
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [2]:
w1, w2, w3 = 0.3, 0.2, 0.5
weight = [w1, w2, w3]

(kanto[0] * weight[0]) + (kanto[1] * weight[1]) + (kanto[2] + weight[2])

78.8

In [3]:
%%time
def crop_yield(region, weights):
    result =0
    for x, w in zip(region, weight):
        result = result + x*w
    return result

CPU times: total: 0 ns
Wall time: 0 ns


In [4]:
%%time
crop_yield(kanto,weight)

CPU times: total: 0 ns
Wall time: 0 ns


56.8

In [5]:
!pip install numpy --upgrade

     -------------------------------------- 14.8/14.8 MB 207.6 kB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.0
    Uninstalling numpy-1.24.0:
      Successfully uninstalled numpy-1.24.0


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [6]:
import numpy as np

In [7]:
kanto = np.array([73, 67,43])
kanto

array([73, 67, 43])

In [8]:
type(kanto)

numpy.ndarray

In [9]:
weights = np.array([w1,w2,w3])
weights

array([0.3, 0.2, 0.5])

In [10]:
type(weights)

numpy.ndarray

In [11]:
dotProduct = np.dot(kanto, weights)
dotProduct

56.8

### Performance Comparision of Python Arrays & Numpy ndArray 

In [12]:
#Python List
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

#Numpy ndArray
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [13]:
%%time
#Calculating Dot Product in List

result =0
for x1, x2 in zip(arr1, arr2):
    result += x1 * x2
result

CPU times: total: 78.1 ms
Wall time: 129 ms


833332333333500000

In [14]:
%%time
#Calculating dot Product  using numpy
dot = np.dot(arr1_np, arr2_np)
dot

CPU times: total: 0 ns
Wall time: 999 µs


-1942957984

## Working with multidimensional Arrays in numpy

In [20]:
climate_data = np.array([[73, 67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]])


In [16]:
weights

array([0.3, 0.2, 0.5])

In [18]:
matrixMultiplication = np.matmul(climate_data, weights)
matrixMultiplication

array([56.8, 76.9])

In [19]:
climate_data @ weights

array([56.8, 76.9])